export default {
    welcomeMessage: 'Welkom',
    active_language: 'ACTIEVE TAAL',
    dashboard: 'Dashboard',
    profile: 'Profiel',
    tickets: 'Tickets',
    invoices: 'Facturen',
    services: 'Diensten',
    team: 'Team',
    see_all_tickets: 'Bekijk alle tickets',
    ticket_number: 'Ticket Nummer',
    title: 'Titel',
    date: 'Datum',
    type: 'Type',
    priority: 'Prioriteit',
    status: 'Status',
    language: 'Actieve taal',
    signOut: 'Uitloggen',
    my_tenant: 'Mijn Tenant',
    organization_information: 'Organisatie Informatie',
    invoices_page: 'Uw facturen, meneer',
    services_no_way: 'Diensten, geen manier',
    token: 'TEKEN',
    active_relation: 'Actieve Relatie',
    permissions: 'Permissies',
    search: 'Zoeken',
    showOpenTickets: 'Toon Open Tickets',
    showAll: 'Toon Alles',
    createTicket: 'Ticket Aanmaken',
    createNewTicket: 'Nieuw kaartje maken',
    cancel: 'Annuleren',
    create:'Creëren',
    date_time_created: 'Datum/tijd Gemaakt',
    created: 'Gemaakt',
    description: 'Beschrijving',
    random_description: 'Willekeurige Beschrijving',
    add_comments: 'Commentaar toevoegen',
    send: 'Versturen',
    comment_added: 'Reactie succesvol toegevoegd!',
    information: 'Informatie',
    attachments: 'Bijlagen',
    recent_tickets: '  Recente tickets',
    show_all: 'Toon alles',
    description_title: 'Omschrijving',
    ticket_title: 'Titel',
    upload_attachment: 'Upload bijlages',
    attach_files: 'Upload bijlages'
    // other Dutch translations...
}
